 cat << EOF > ./99-worker-kdump-configuration.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-kdump-configuration
spec:
  kernelArguments:
    - 'crashkernel=256M' 
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,cGF0aCAvdmFyL2NyYXNoCmNvcmVfY29sbGVjdG9yIG1ha2VkdW1wZmlsZSAtbCAtLW1lc3NhZ2UtbGV2ZWwgNyAtZCAzMQo=  
          mode: 420
          overwrite: true
          path: /etc/kdump.conf
        - contents:
            source: data:text/plain;charset=utf-8;base64,S0RVTVBfQ09NTUFORExJTkVfUkVNT1ZFPSJodWdlcGFnZXMgaHVnZXBhZ2VzeiBzbHViX2RlYnVnIHF1aWV0IGxvZ19idWZfbGVuIHN3aW90bGIiCktEVU1QX0NPTU1BTkRMSU5FX0FQUEVORD0iaXJxcG9sbCBucl9jcHVzPTEgcmVzZXRfZGV2aWNlcyBjZ3JvdXBfZGlzYWJsZT1tZW1vcnkgbWNlPW9mZiBudW1hPW9mZiB1ZGV2LmNoaWxkcmVuLW1heD0yIHBhbmljPTEwIHJvb3RmbGFncz1ub2ZhaWwgYWNwaV9ub19tZW1ob3RwbHVnIHRyYW5zcGFyZW50X2h1Z2VwYWdlPW5ldmVyIG5va2FzbHIgbm92bWNvcmVkZCBoZXN0X2Rpc2FibGUiCktFWEVDX0FSR1M9Ii1zIgpLRFVNUF9JTUc9InZtbGludXoiCg==  
          mode: 420
          overwrite: true
          path: /etc/sysconfig/kdump
    systemd:
      units:
        - enabled: true
          name: kdump.service
EOF
oc create -f ./99-worker-kdump-configuration.yaml

